CSV_TO_MODEL_MAPPING = {
    'tender/title': 'title',
    'buyer/name': 'buyer_name',
    'Fiscal Year': 'fiscal_year',
    'ocid': 'ocid',
    'initiationType': 'initiation_type',
    'tag': 'tag',
    'id': 'data_id',
    'date': 'date',
    'tender/id': 'tender_id',
    'tender/externalReference': 'tender_externalreference',
    'tender/mainProcurementCategory': 'tender_mainprocurementcategory',
    'tender/procurementMethod': 'tender_procurementmethod',
    'tender/contractType': 'tender_contracttype',
    'tenderclassification/description': 'tenderclassification_description',
    'tender/submissionMethodDetails': 'tender_submission_method_details',
    'tender/participationFee/0/multiCurrencyAllowed': 'tender_participationFee_0_multicurrencyallowed',
    'tender/allowTwoStageTender': 'tender_allowtwostagetender',
    'tender/value/amount': 'tender_value_amount',
    'tender/datePublished': 'tender_datepublished',
    'tender/milestones/dueDate': 'tender_milestones_duedate',
    'tender/tenderPeriod/durationInDays': 'tender_tenderperiod_durationindays',
    'tender/allowPreferentialBidder': 'tender_allowpreferentialbidder',
    'Payment Mode': 'payment_mode',
    'tender/status': 'tender_status',
    'tender/stage': 'tender_stage',
    'tender/numberOfTenderers': 'tender_numberoftenderers',
    'tender/bidOpening/date': 'tender_bid_opening_date',
    'tender/milestones/title': 'tender_milestones_title',
    'tender/documents/id': 'tender_documents_id'
}
